version: "3.8"

services:
  backend:
    build: ./api-bs
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:mydb
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true

  frontend:
    build: ./frontend-bs
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend



volumes:
  db_data:
